'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, ChevronDown, Code2, Database, FileText, Menu, Play, Sparkles, Target, UserRound, X, Zap } from 'lucide-react'

const roles = {
  Frontend: { icon: Code2, question: 'How would you optimize a React application that is rendering slowly?', tags: ['React', 'Performance', 'Architecture'] },
  Backend: { icon: Database, question: 'Design an API that handles millions of requests with low latency.', tags: ['APIs', 'Scalability', 'Systems'] },
  Data: { icon: BarChart3, question: 'How would you explain a model&apos;s precision and recall to a stakeholder?', tags: ['SQL', 'Modeling', 'Analysis'] },
}

const faqs = [
  ['What is Simiu?', 'Simiu is an AI-powered practice space and junior job board that helps you turn interview nerves into confident, repeatable performance.'],
  ['Is Simiu free to use?', 'Early access members will get a generous free plan, with optional upgrades for deeper feedback and more practice sessions.'],
  ['Who is Simiu for?', 'Simiu is built for students, self-taught developers, bootcamp grads, and anyone looking for their first role in tech.'],
  ['When does Simiu launch?', 'We are inviting our first group of candidates soon. Join the list and you will be first to know when your spot opens.'],
]

function Logo() { return <a href="#top" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></span><span className="text-lg">simiu<span className="text-primary">.</span></span></a> }

export default function Home() {
  const [role, setRole] = useState<keyof typeof roles>('Frontend')
  const [email, setEmail] = useState('')
  const [joined, setJoined] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const [mobileOpen, setMobileOpen] = useState(false)
  const current = roles[role]
  const RoleIcon = current.icon

  function submit(e: React.FormEvent) { e.preventDefault(); if (email.trim()) setJoined(true) }

  return <div id="top" className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#features" className="transition hover:text-foreground">Why Simiu</a><a href="#how" className="transition hover:text-foreground">How it works</a><a href="#faq" className="transition hover:text-foreground">FAQ</a></nav><a href="#waitlist" className="hidden rounded-full bg-foreground px-5 py-2.5 text-sm font-medium text-background transition hover:bg-primary hover:text-primary-foreground md:block">Join early access <ArrowRight className="ml-1 inline size-4" /></a><button aria-label="Toggle menu" onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 md:hidden">{mobileOpen ? <X /> : <Menu />}</button></header>
    {mobileOpen && <nav className="mx-5 flex flex-col gap-4 border-b border-border pb-5 text-sm md:hidden"><a href="#features" onClick={() => setMobileOpen(false)}>Why Simiu</a><a href="#how" onClick={() => setMobileOpen(false)}>How it works</a><a href="#faq" onClick={() => setMobileOpen(false)}>FAQ</a><a href="#waitlist" onClick={() => setMobileOpen(false)} className="text-primary">Join early access →</a></nav>}

    <main>
      <section className="relative mx-auto grid max-w-6xl items-center gap-16 px-5 pb-24 pt-16 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-32 lg:pt-28"><div className="pointer-events-none absolute -left-40 top-10 size-96 rounded-full bg-primary/10 blur-3xl" /><div className="relative"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary"><span className="size-1.5 animate-pulse rounded-full bg-primary" /> Now welcoming our first 1,000 candidates</div><h1 className="max-w-2xl text-balance text-5xl font-semibold leading-[1.05] tracking-[-0.05em] sm:text-6xl lg:text-7xl">Your next role starts with a <span className="text-primary">better answer.</span></h1><p className="mt-6 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">Practice real interviews with an AI that gives you useful feedback. Find junior roles that match your potential.</p><form id="waitlist" onSubmit={submit} className="mt-8 flex max-w-md flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="email">Your email address</label><input id="email" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@email.com" className="min-w-0 flex-1 rounded-xl border border-border bg-card px-4 py-3.5 text-sm outline-none ring-primary transition placeholder:text-muted-foreground focus:ring-2" /><button className="rounded-xl bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground transition hover:brightness-110">{joined ? <><Check className="mr-1 inline size-4" /> You&apos;re on the list</> : <>Get early access <ArrowRight className="ml-1 inline size-4" /></>}</button></form><p className="mt-3 text-xs text-muted-foreground">No spam. Just your invite when we&apos;re ready.</p></div>
        <div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-4 rounded-[2rem] bg-primary/10 blur-2xl" /><div className="relative rounded-3xl border border-border bg-card p-4 shadow-2xl shadow-black/20 sm:p-5"><div className="flex items-center justify-between border-b border-border pb-4"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary/15 text-primary"><RoleIcon className="size-4" /></span><div><p className="text-xs font-medium text-muted-foreground">AI interview session</p><p className="text-sm font-semibold">Frontend · Question 04</p></div></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs font-medium text-emerald-400">Live feedback</span></div><div className="mt-5 rounded-2xl bg-background p-5"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Play className="size-3 fill-current text-primary" /> Your answer · 01:42</div><p className="mt-3 text-sm leading-6 text-foreground/80">“I&apos;d start by checking the component tree and looking for unnecessary re-renders...”</p><div className="mt-5 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Overall score</p><p className="mt-1 text-5xl font-semibold tracking-tight">8.4<span className="text-xl text-muted-foreground">/10</span></p></div><div className="grid size-20 place-items-center rounded-full border-[6px] border-emerald-400/25 border-t-emerald-400 text-lg font-semibold text-emerald-400">84%</div></div></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl bg-background p-3"><p className="text-[11px] text-muted-foreground">Clarity</p><p className="mt-1 text-sm font-semibold">Great</p></div><div className="rounded-xl bg-background p-3"><p className="text-[11px] text-muted-foreground">Technical</p><p className="mt-1 text-sm font-semibold">Strong</p></div><div className="rounded-xl bg-background p-3"><p className="text-[11px] text-muted-foreground">Tip</p><p className="mt-1 text-sm font-semibold text-primary">+1.2 pts</p></div></div></div></div>
      </section>

      <section id="features" className="border-y border-border bg-card/40"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="max-w-xl"><p className="text-sm font-semibold text-primary">BUILT FOR THE LEAP</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Everything you need to go from learning to landing.</h2></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{[[Target,'Practice with purpose','Questions tailored to the role you actually want.'],[Zap,'Feedback that clicks','Clear, specific coaching you can use on your next answer.'],[BriefcaseBusiness,'Find your fit','A junior job board curated for early-career talent.'],[UserRound,'Show up confident','Build the muscle memory that makes interviews feel natural.']].map(([Icon,title,copy]) => <div key={title as string} className="bg-background p-6"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="mt-5 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy as string}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold text-primary">PRACTICE YOUR WAY</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A smarter way to prepare for what&apos;s next.</h2><p className="mt-4 leading-7 text-muted-foreground">Pick a path, get in the room, and leave every session better than you entered it.</p></div><div><div className="flex gap-2 border-b border-border pb-3">{(Object.keys(roles) as (keyof typeof roles)[]).map(item => <button key={item} onClick={() => setRole(item)} className={`rounded-lg px-4 py-2 text-sm font-medium transition ${role === item ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div><div className="mt-6 rounded-2xl border border-border bg-card p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><RoleIcon className="size-5" /></span><div><p className="text-xs text-muted-foreground">Sample {role} question</p><p className="font-medium">Question 01</p></div></div><p className="mt-7 text-xl font-medium leading-8">{current.question}</p><div className="mt-6 flex flex-wrap gap-2">{current.tags.map(tag => <span key={tag} className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">{tag}</span>)}</div></div></div></div></section>

      <section id="how" className="border-y border-border bg-card/40"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="text-center"><p className="text-sm font-semibold text-primary">HOW IT WORKS</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Three steps closer to yes.</h2></div><div className="mt-14 grid gap-8 md:grid-cols-3">{[[FileText,'Choose your path','Tell us the role you want and we&apos;ll build a practice plan around it.'],[Play,'Take the interview','Answer voice or text questions in a realistic, low-pressure room.'],[Sparkles,'Level up fast','Get instant feedback, track your progress, and apply with confidence.']].map(([Icon,title,copy],i) => <div key={title as string} className="relative"><span className="text-5xl font-semibold tracking-tighter text-primary/30">0{i+1}</span><div className="mt-4 flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></div><h3 className="mt-5 text-lg font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy as string}</p></div>)}</div></div></section>

      <section id="faq" className="mx-auto max-w-3xl px-5 py-24 lg:px-8"><div className="text-center"><p className="text-sm font-semibold text-primary">FAQ</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Good questions. We have answers.</h2></div><div className="mt-10 divide-y divide-border border-y border-border">{faqs.map(([q,a],i) => <div key={q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)} className="flex w-full items-center justify-between gap-6 py-5 text-left font-medium"><span>{q}</span><ChevronDown className={`size-5 shrink-0 text-muted-foreground transition ${openFaq === i ? 'rotate-180 text-primary' : ''}`} /></button>{openFaq === i && <p className="max-w-2xl pb-5 text-sm leading-7 text-muted-foreground">{a}</p>}</div>)}</div></section>

      <section className="mx-5 mb-20 overflow-hidden rounded-3xl bg-primary px-6 py-14 text-center text-primary-foreground sm:px-12 lg:mx-auto lg:max-w-6xl"><p className="text-sm font-semibold uppercase tracking-widest text-primary-foreground/70">Your future self will thank you</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">The next interview is a practice run away.</h2><p className="mx-auto mt-4 max-w-lg text-primary-foreground/75">Join the first wave of candidates building careers with a little more confidence.</p><a href="#waitlist" className="mt-8 inline-flex items-center rounded-xl bg-background px-5 py-3.5 text-sm font-semibold text-foreground transition hover:bg-background/80">Join early access <ArrowRight className="ml-2 size-4" /></a></section>
    </main><footer className="mx-auto flex max-w-6xl flex-col gap-5 border-t border-border px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><Logo /><p>© 2026 Simiu. Built for the next generation.</p><div className="flex gap-5"><a href="#faq" className="hover:text-foreground">Privacy</a><a href="#faq" className="hover:text-foreground">Contact</a></div></footer>
  </div>
}
