'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, BriefcaseBusiness, Check, ChevronDown, Code2, Database, FileText, Menu, Play, Quote, Sparkles, Target, UserRound, X, Zap } from 'lucide-react'

const roles = {
  Frontend: { icon: Code2, question: 'How would you optimize a React application that is rendering slowly?', tags: ['React', 'Performance', 'Architecture'] },
  Backend: { icon: Database, question: 'Design an API that handles millions of requests with low latency.', tags: ['APIs', 'Scalability', 'Systems'] },
  Data: { icon: BarChart3, question: 'How would you explain a model&apos;s precision and recall to a stakeholder?', tags: ['SQL', 'Modeling', 'Analysis'] },
}

const faqs = [
  ['What is Simiu?', 'Simiu is an AI-powered practice space and junior job board that helps you turn interview nerves into confident, repeatable performance.'],
  ['Is Simiu free to use?', 'Early access members will get a generous free plan, with optional upgrades for deeper feedback and more practice sessions.'],
  ['Who is Simiu for?', 'Simiu is built for students, self-taught developers, bootcamp grads, and anyone looking for their first role in tech.'],
  ['When does Simiu launch?', 'We are inviting our first group of candidates soon. Join the list and you will be first to know when your spot opens.'],
]

function Logo() {
  return <a href="#top" className="flex items-center gap-3 font-semibold tracking-tight"><span className="room-mark" aria-hidden="true">“_</span><span className="font-serif text-xl">simiu</span></a>
}

export default function Home() {
  const [role, setRole] = useState<keyof typeof roles>('Frontend')
  const [email, setEmail] = useState('')
  const [joined, setJoined] = useState(false)
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const [mobileOpen, setMobileOpen] = useState(false)
  const current = roles[role]

  function submit(e: React.FormEvent) { e.preventDefault(); if (email.trim()) setJoined(true) }

  return <div id="top" className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="/about" className="transition hover:text-foreground">About</a><a href="/services" className="transition hover:text-foreground">Services</a><a href="/contact" className="transition hover:text-foreground">Contact</a></nav><a href="#waitlist" className="hidden rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition hover:brightness-110 md:block">Join early access <ArrowRight className="ml-1 inline size-4" /></a><button aria-label="Toggle menu" onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 md:hidden">{mobileOpen ? <X /> : <Menu />}</button></header>
    {mobileOpen && <nav className="mx-5 flex flex-col gap-4 border-b border-border pb-5 text-sm md:hidden"><a href="/about" onClick={() => setMobileOpen(false)}>About</a><a href="/services" onClick={() => setMobileOpen(false)}>Services</a><a href="/contact" onClick={() => setMobileOpen(false)}>Contact</a><a href="#waitlist" onClick={() => setMobileOpen(false)} className="text-primary">Join early access →</a></nav>}

    <main>
      <section className="mx-auto grid max-w-6xl items-center gap-14 px-5 pb-24 pt-16 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:pb-32 lg:pt-24"><div><p className="mb-6 text-sm text-muted-foreground">A calmer way into your first tech role.</p><h1 className="max-w-2xl text-balance font-serif text-5xl leading-[1.04] tracking-[-0.035em] sm:text-6xl lg:text-7xl">Practice until confidence feels <em className="text-primary">familiar.</em></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">Simiu gives you a quiet place to practice real interviews, understand your gaps, and find junior roles that match your potential.</p><form id="waitlist" onSubmit={submit} className="mt-8 flex max-w-md flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="email">Your email address</label><input id="email" type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@email.com" className="min-w-0 flex-1 rounded-xl border border-border bg-card px-4 py-3.5 text-sm outline-none transition placeholder:text-muted-foreground focus:ring-2 focus:ring-primary" /><button className="rounded-xl bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground transition hover:brightness-110">{joined ? <><Check className="mr-1 inline size-4" /> You&apos;re on the list</> : <>Get early access <ArrowRight className="ml-1 inline size-4" /></>}</button></form><p className="mt-3 text-xs text-muted-foreground">No spam. Just your invite when we&apos;re ready.</p><div className="mt-10 flex items-start gap-3 border-t border-border pt-5"><Quote className="mt-1 size-4 shrink-0 text-primary" /><div><p className="text-sm leading-6 text-foreground/85">“It feels like having a patient mentor in the room.”</p><p className="mt-1 text-xs text-muted-foreground">Maya R., bootcamp grad · <span className="text-primary">1,247 early candidates on the list</span></p></div></div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="transcript-card rounded-3xl p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between border-b border-ink/15 pb-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-ink/55">Interview room / 04</p><p className="mt-1 font-serif text-xl text-ink">Frontend fundamentals</p></div><span className="flex items-center gap-2 text-xs font-medium text-ink/60"><span className="size-2 rounded-full bg-signal" /> Recording</span></div><div className="mt-6 grid gap-5 sm:grid-cols-[1fr_150px]"><div><div className="flex items-center gap-2 text-xs text-ink/55"><Play className="size-3 fill-current" /> Your answer · 01:42</div><p className="ruled-paper mt-3 rounded-xl p-4 font-serif text-lg leading-8 text-ink">“I&apos;d start by checking the component tree and looking for <mark>unnecessary re-renders</mark>...”</p><div className="mt-4 flex gap-3 rounded-xl border border-ink/10 bg-white/35 p-3"><Sparkles className="mt-0.5 size-4 shrink-0 text-indigo" /><p className="text-xs leading-5 text-ink/75"><strong className="text-ink">AI coach</strong><br />Strong instinct — name the tradeoff next time.</p></div></div><div className="flex flex-col justify-between"><div><p className="text-xs uppercase tracking-widest text-ink/50">Coach&apos;s read</p><p className="mt-2 font-serif text-5xl text-ink">8.4<span className="text-xl text-ink/50">/10</span></p></div><div className="space-y-3 border-t border-ink/15 pt-3 text-xs text-ink/70"><div className="flex justify-between"><span>Clarity</span><strong>Great</strong></div><div className="flex justify-between"><span>Depth</span><strong>Strong</strong></div><div className="flex justify-between"><span>Confidence</span><strong>Growing</strong></div></div></div></div></div></div>
      </section>

      <section id="features" className="border-y border-border bg-card/35"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="max-w-xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">Built for the leap</p><h2 className="mt-4 font-serif text-4xl tracking-tight sm:text-5xl">Everything you need to go from learning to landing.</h2></div><div className="mt-12 grid gap-x-8 gap-y-10 sm:grid-cols-2 lg:grid-cols-4">{[[Target,'Practice with purpose','Questions tailored to the role you actually want.'],[Zap,'Feedback that clicks','Clear, specific coaching you can use on your next answer.'],[BriefcaseBusiness,'Find your fit','A junior job board curated for early-career talent.'],[UserRound,'Show up confident','Build the muscle memory that makes interviews feel natural.']].map(([Icon,title,copy]) => <div key={title as string} className="border-t border-border pt-5"><Icon className="size-5 text-primary" /><h3 className="mt-5 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy as string}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm text-muted-foreground">Choose your room</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">A smarter way to prepare for what&apos;s next.</h2><p className="mt-4 leading-7 text-muted-foreground">Pick a path, get in the room, and leave every session better than you entered it.</p></div><div><div className="flex gap-1 border-b border-border pb-3">{(Object.keys(roles) as (keyof typeof roles)[]).map(item => <button key={item} onClick={() => setRole(item)} className={`rounded-lg px-4 py-2 text-sm font-medium transition ${role === item ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div><div className="mt-6 rounded-2xl border border-border bg-card p-6"><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">Sample {role} question · 01</p><p className="mt-7 font-serif text-2xl leading-9">{current.question}</p><div className="mt-7 flex flex-wrap gap-2">{current.tags.map(tag => <span key={tag} className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground">{tag}</span>)}</div></div></div></div></section>

      <section id="how" className="border-y border-border bg-card/35"><div className="mx-auto max-w-6xl px-5 py-20 lg:px-8"><div className="max-w-md"><p className="text-sm text-muted-foreground">How it works</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Three steps closer to yes.</h2></div><div className="mt-14 grid gap-8 md:grid-cols-3">{[[FileText,'Choose your path','Tell us the role you want and we&apos;ll build a practice plan around it.'],[Play,'Take the interview','Answer voice or text questions in a realistic, low-pressure room.'],[Sparkles,'Level up fast','Get instant feedback, track your progress, and apply with confidence.']].map(([Icon,title,copy]) => <div key={title as string} className="border-t border-border pt-5"><div className="flex size-10 items-center justify-center rounded-full bg-primary/15 text-primary"><Icon className="size-5" /></div><h3 className="mt-5 text-lg font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy as string}</p></div>)}</div></div></section>

      <section id="faq" className="mx-auto max-w-3xl px-5 py-24 lg:px-8"><div className="text-center"><p className="text-sm text-muted-foreground">A few things you might be wondering</p><h2 className="mt-3 font-serif text-4xl tracking-tight">Good questions. We have answers.</h2></div><div className="mt-10 divide-y divide-border border-y border-border">{faqs.map(([q,a],i) => <div key={q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)} className={`flex w-full items-center justify-between gap-6 py-6 text-left font-medium ${openFaq === i ? 'text-primary' : ''}`}><span>{q}</span><ChevronDown className={`size-5 shrink-0 text-muted-foreground transition ${openFaq === i ? 'rotate-180 text-primary' : ''}`} /></button>{openFaq === i && <p className="max-w-2xl pb-6 text-sm leading-7 text-muted-foreground">{a}</p>}</div>)}</div></section>

      <section className="mx-5 mb-20 overflow-hidden rounded-3xl bg-primary px-6 py-14 text-center text-primary-foreground sm:px-12 lg:mx-auto lg:max-w-6xl"><h2 className="mx-auto max-w-2xl font-serif text-4xl tracking-tight sm:text-5xl">You don&apos;t have to feel ready to begin.</h2><p className="mx-auto mt-4 max-w-lg text-primary-foreground/75">Join the first wave of candidates building careers with a little more confidence.</p><a href="#waitlist" className="mt-8 inline-flex items-center rounded-xl bg-background px-5 py-3.5 text-sm font-semibold text-foreground transition hover:bg-background/80">Join early access <ArrowRight className="ml-2 size-4" /></a></section>
    </main><footer className="mx-auto flex max-w-6xl flex-col gap-5 border-t border-border px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><Logo /><p>© 2026 Simiu. Made with a little AI, reviewed by humans.</p><div className="flex gap-5"><a href="/about" className="hover:text-foreground">About</a><a href="/contact" className="hover:text-foreground">Contact</a></div></footer>
  </div>
}
